### ISSUE TITLE
Papa's Freezeria Missing Text

### ISSUE THREAD

**Issue by WorldOfStrife** [CBGamesdev/chilibowlflash#10]
Buttons in some of the menus are missing text, and the drinks are missing color (the cups look clear).

Let me know if these images don't load. Thanks.

![image](https://user-images.githubusercontent.com/116005205/196205863-4cfecba6-fea5-43ea-bfde-6fb2321ee4ae.png)

![image](https://user-images.githubusercontent.com/116005205/196207166-09174fae-e75e-43f2-8a9c-a1b481d8bcef.png)

![image](https://user-images.githubusercontent.com/116005205/196207280-b19c85c4-e0bf-4d0c-a21e-a7ab362f6620.png)

**Comment by CBGamesdev** [comment]
a lot of the papa's games are very buggy because of the WIP of the emulator used, unfortunately there's not really a fix I could do unless I upload a new swf file which woudl reset peoples progress and do more harm than good, I'd think.

**Comment by CBGamesdev** [comment]
I have it on ruffle now
