### ISSUE TITLE
Grammar Issues

### ISSUE THREAD

**Issue by cootshk** [CBGamesdev/chilibowlflash#14]
Old:
”If **somethings** goes **wrong please** report an error at the **[Github.](https://github.com/CBGamesdev/chiliblox)** Thanks and Enjoy!!”
New:
If **something** goes **wrong,** please report an error on [Github](https://github.com/CBGamesdev/chiliblox)**.**  Thanks and Enjoy!!

**Comment by CBGamesdev** [comment]
yeah i put that in late at night years ago and never changed it out of laziness, guess i will now huh
