### ISSUE TITLE
Hello there!

### ISSUE THREAD

**Issue by 3kh0** [CBGamesdev/chilibowlflash#2]
I noticed that you had added my slope game I would like for you to use a different format. There is a updated version on my site right now.

[View it here](https://3kh0.github.io/slope/)

**Comment by CBGamesdev** [comment]
Woah, thanks for noticing! Right now I cant get this version to work on my hardware, but, when I can get it, I´ll update it. Thanks again for reaching out. Oh, and coding the game.

**Comment by CBGamesdev** [comment]
I am going to add another persons slope, because I cannot get your updated versions code. Thank you for it though!

**Comment by 3kh0** [comment]
Also I have a site where I have lots of games that you can link to
