### ISSUE TITLE
pleez h3lp!!

### ISSUE THREAD

**Issue by kimobloop** [CBGamesdev/chilibowlflash#25]
so i w4s bored and wanted t0 play papa's fr33zeria but it just went to black and it wont l0ad at a1l, pleez help idk whatz happening but i rly w4nna play papa'z fr3ezeri4 (TTATT)

**Comment by CBGamesdev** [comment]
hey, sorry about that issue. I have to get a new version of waflash or just transfer them to ruffle (different emulators and stuff)

**Comment by CBGamesdev** [comment]
updated wasflash, most games should work as they were, including saves being the same.
