### ISSUE TITLE
How do i embed it to google sites

### ISSUE THREAD

**Issue by GinjaNinja420** [CBGamesdev/chilibowlflash#30]

**Comment by CBGamesdev** [comment]
if you're using new google sites (which is assume you are as you can't even make old google sites lol) there should be a button to the right labeled "embed". It's icon should be yellow and look like this: <>. Click it and paste the url of the game you want after it (fort example, say you want to embed papas pizzaria, you would need to go to the home page: cbgamesdev.github.io, then click on papas pizzaria: https://cbgamesdev.github.io/chilibowlflash/papapizza.html, and copy that link into the box that shows up while editing your google site. It should be set to "By URL". Hope this helps.
