### ISSUE TITLE
all games are blocked by lightspeed filter agent including main chilibowl website. Blocking is listed as: Local Deny

### ISSUE THREAD

**Issue by TavitFromSchool** [CBGamesdev/chilibowlflash#35]

**Comment by CBGamesdev** [comment]
Odd, I have to make a new backup and if the problem persists than I have to take this code elsewhere.

**Comment by DmitriVoooozikooo** [comment]
I'm pretty sure 'local deny' is where your local area denies access for some reason or the specific device with the lightspeed filter agent always blocks it. It's a more specific categorization so I think it's set by a more important figure at your school

**Comment by CBGamesdev** [comment]
probaly, i know mine has blocked cbgamesdev so i created chiboga as a backup
