### ISSUE TITLE
NES Games Not Working

### ISSUE THREAD

**Issue by FLOOFYBULL** [CBGamesdev/chilibowlflash#4]
All the NES games don't work when embedded on a google site for use on a school computer

**Comment by CBGamesdev** [comment]
It's most likely because your school has blocked our host site, and thus embedding it doesn´t change that. 

I´m working on hosting this on another account, and have that one be unblocked for some time. Rinse and Repeat.

**Comment by ChiBoGa** [comment]
try the new one:

https://chiboga.github.io/
